mw.loader.using('mediawiki.util',function(){if(mw.config.get('wgArticleId')===0&&mw.config.get('wgNamespaceNumber')==2){var titleParts=mw.config.get('wgPageName').split('/');if(titleParts.length==2){var userSkinPage=titleParts.shift()+'/'+mw.config.get('skin');if(titleParts.slice(-1)=='skin.js'){window.location.href=mw.util.wikiGetlink(userSkinPage+'.js');}else if(titleParts.slice(-1)=='skin.css'){window.location.href=mw.util.wikiGetlink(userSkinPage+'.css');}}}var autoCollapse=2;var collapseCaption="hide";var expandCaption="show";window.collapseTable=function(tableIndex){var Button=document.getElementById("collapseButton"+tableIndex);var Table=document.getElementById("collapsibleTable"+tableIndex);if(!Table||!Button){return false;}var Rows=Table.rows;if(Button.firstChild.data==collapseCaption){for(var i=1;i<Rows.length;i++){Rows[i].style.display="none";}Button.firstChild.data=expandCaption;}else{for(var i=1;i<Rows.length;i++){Rows[i].style.display=Rows[0].style.display;}Button.
firstChild.data=collapseCaption;}}
function createCollapseButtons(){var tableIndex=0;var NavigationBoxes=new Object();var Tables=document.getElementsByTagName("table");for(var i=0;i<Tables.length;i++){if(hasClass(Tables[i],"collapsible")){var HeaderRow=Tables[i].getElementsByTagName("tr")[0];if(!HeaderRow)continue;var Header=HeaderRow.getElementsByTagName("th")[0];if(!Header)continue;NavigationBoxes[tableIndex]=Tables[i];Tables[i].setAttribute("id","collapsibleTable"+tableIndex);var Button=document.createElement("span");var ButtonLink=document.createElement("a");var ButtonText=document.createTextNode(collapseCaption);Button.className="collapseButton";ButtonLink.style.color=Header.style.color;ButtonLink.setAttribute("id","collapseButton"+tableIndex);ButtonLink.setAttribute("href","#");addHandler(ButtonLink,"click",new Function("evt","collapseTable("+tableIndex+" ); return killEvt( evt );"));ButtonLink.appendChild(ButtonText);Button.appendChild(document.createTextNode("["));Button.appendChild(ButtonLink);Button.
appendChild(document.createTextNode("]"));Header.insertBefore(Button,Header.firstChild);tableIndex++;}}for(var i=0;i<tableIndex;i++){if(hasClass(NavigationBoxes[i],"collapsed")||(tableIndex>=autoCollapse&&hasClass(NavigationBoxes[i],"autocollapse"))){collapseTable(i);}else if(hasClass(NavigationBoxes[i],"innercollapse")){var element=NavigationBoxes[i];while(element=element.parentNode){if(hasClass(element,"outercollapse")){collapseTable(i);break;}}}}}$(createCollapseButtons);var NavigationBarHide='['+collapseCaption+']';var NavigationBarShow='['+expandCaption+']';window.toggleNavigationBar=function(indexNavigationBar){var NavToggle=document.getElementById("NavToggle"+indexNavigationBar);var NavFrame=document.getElementById("NavFrame"+indexNavigationBar);if(!NavFrame||!NavToggle){return false;}if(NavToggle.firstChild.data==NavigationBarHide){for(var NavChild=NavFrame.firstChild;NavChild!=null;NavChild=NavChild.nextSibling){if(hasClass(NavChild,'NavContent')||hasClass(NavChild,'NavPic')){
NavChild.style.display='none';}}NavToggle.firstChild.data=NavigationBarShow;}else if(NavToggle.firstChild.data==NavigationBarShow){for(var NavChild=NavFrame.firstChild;NavChild!=null;NavChild=NavChild.nextSibling){if(hasClass(NavChild,'NavContent')||hasClass(NavChild,'NavPic')){NavChild.style.display='block';}}NavToggle.firstChild.data=NavigationBarHide;}}
function createNavigationBarToggleButton(){var indexNavigationBar=0;var NavFrame;var NavChild;var divs=document.getElementsByTagName('div');for(var i=0;(NavFrame=divs[i]);i++){if($(NavFrame).hasClass('NavFrame')){indexNavigationBar++;var NavToggle=document.createElement('a');NavToggle.className='NavToggle';NavToggle.setAttribute('id','NavToggle'+indexNavigationBar);NavToggle.setAttribute('href','#');$(NavToggle).on('click',$.proxy(window.toggleNavigationBar,window,indexNavigationBar));var isCollapsed=$(NavFrame).hasClass('collapsed');for(NavChild=NavFrame.firstChild;NavChild!=null&&!isCollapsed;NavChild=NavChild.nextSibling){if($(NavChild).hasClass('NavPic')||$(NavChild).hasClass('NavContent')){if(NavChild.style.display==='none'){isCollapsed=true;}}}if(isCollapsed){for(NavChild=NavFrame.firstChild;NavChild!=null;NavChild=NavChild.nextSibling){if($(NavChild).hasClass('NavPic')||$(NavChild).hasClass('NavContent')){NavChild.style.display='none';}}}var NavToggleText=document.createTextNode
(isCollapsed?NavigationBarShow:NavigationBarHide);NavToggle.appendChild(NavToggleText);for(var j=0;j<NavFrame.childNodes.length;j++){if($(NavFrame.childNodes[j]).hasClass('NavHead')){NavToggle.style.color=NavFrame.childNodes[j].style.color;NavFrame.childNodes[j].appendChild(NavToggle);}}NavFrame.setAttribute('id','NavFrame'+indexNavigationBar);}}}$(createNavigationBarToggleButton);});;mw.loader.state({"site":"ready"});

/* cache key: docsj_mediawiki:resourceloader:filter:minify-js:7:1accff4ca5b02a3a2b31bbe0d62d23cf */

/* Cached 20130520070317 */